### ISSUE TITLE
Support for python 3.10 / 3.11

### ISSUE THREAD

**Issue by j-riebe** [user01/rdp-rust#13]
@user01 Is it possible to add support for python 3.10 and eventually the 3.11 pre-release version?

**Comment by user01** [comment]
Updated the project to build with ABI37, so should be compatible with >=3.7 with package version >=0.5.3

@j-riebe let me know if the wheels work? They have been published to pypi

**Comment by j-riebe** [comment]
@user01 Thanks! 

The installation seems to work (tested with docker - see below).

```
docker run -it python:3.10-bullseye pip install rdp-rust
docker run -it python:3.11-rc-bullseye pip install rdp-rust
```
